// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZffb1VQ-pn0YE_UUt-jPYfUd13RJ7cno',
    appId: '1:936005766674:web:3298387161e8a84ca612cb',
    messagingSenderId: '936005766674',
    projectId: 'saran-portfolio-76b1f',
    authDomain: 'saran-portfolio-76b1f.firebaseapp.com',
    storageBucket: 'saran-portfolio-76b1f.firebasestorage.app',
    measurementId: 'G-8YMR3RP8RJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7b8Kxz3W3rfxd3DfS0UPhd9-3LqGwbuA',
    appId: '1:936005766674:android:d25265e25e2d7a20a612cb',
    messagingSenderId: '936005766674',
    projectId: 'saran-portfolio-76b1f',
    storageBucket: 'saran-portfolio-76b1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2dIQIKTn1YnuG0Y60TGAAMbRhg3zIVj8',
    appId: '1:936005766674:ios:15031cd1bbecce38a612cb',
    messagingSenderId: '936005766674',
    projectId: 'saran-portfolio-76b1f',
    storageBucket: 'saran-portfolio-76b1f.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2dIQIKTn1YnuG0Y60TGAAMbRhg3zIVj8',
    appId: '1:936005766674:ios:15031cd1bbecce38a612cb',
    messagingSenderId: '936005766674',
    projectId: 'saran-portfolio-76b1f',
    storageBucket: 'saran-portfolio-76b1f.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZffb1VQ-pn0YE_UUt-jPYfUd13RJ7cno',
    appId: '1:936005766674:web:87ab97d885bcdd3ba612cb',
    messagingSenderId: '936005766674',
    projectId: 'saran-portfolio-76b1f',
    authDomain: 'saran-portfolio-76b1f.firebaseapp.com',
    storageBucket: 'saran-portfolio-76b1f.firebasestorage.app',
    measurementId: 'G-LWYPSMTRKH',
  );
}
